### ISSUE TITLE
Remove version pin for pip

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3037]
When installing Python dependencies, we currently always use pip 24.0 instead of the latest version.

https://github.com/posit-dev/positron/blob/ed7ad00efad489a0d5de1b4551e70f3cfa78f681/extensions/positron-python/python_files/download_get_pip.py#L14-L18

This is because using the "latest" version currently results in this error:

```
[22:15:25] Error: Failed to download get-pip.py using 'python'
    at /Users/user229818/actions-runner/_work/positron/positron/extensions/positron-python/gulpfile.js:332:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user229818/actions-runner/_work/positron/positron/extensions/positron-python/gulpfile.js:327:5
[22:15:25] 'installPythonLibs' errored after 12 s
```

(full logs: https://github.com/posit-dev/positron/actions/runs/8978604109)

... which in turn is because the "latest" version is `24.1b1` which doesn't have a working download URL.

Once this error has been cleared upstream, we should consider peeling off our band-aid and returning to the previous behavior.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : N/A
    OS Version          : N/A

### Test scenario(s) 

Validated based on code examination.

Link(s) to TestRail test cases run or created:
