### ISSUE TITLE
Comms created by kernels are not correctly disposed on runtime shutdown

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#3964]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 21

## Steps to reproduce the issue:

1. Create a plot in either Python or R.

    ```python
    # Python
    import matplotlib.pyplot as plt; plt.plot([0,1])
    ```

    ```r
    # R
    plot(0:1)
    ```
2. Shutdown the runtime.
3. You'll see a few errors in the console logs.

## What did you expect to happen?
There shouldn't be any console errors.

## Were there any error messages in the output or Developer Tools console?

<details>
<summary>Console Logs</summary>

```
workbench.desktop.main.js:61148 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of null (reading 'title') (at console.<anonymous> (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62216:26))
log @ workbench.desktop.main.js:61148
$logExtensionHostMessage @ workbench.desktop.main.js:342302
S @ workbench.desktop.main.js:342953
Q @ workbench.desktop.main.js:342938
M @ workbench.desktop.main.js:342879
L @ workbench.desktop.main.js:342806
(anonymous) @ workbench.desktop.main.js:342669
y @ workbench.desktop.main.js:17356
fire @ workbench.desktop.main.js:17385
fire @ workbench.desktop.main.js:93228
port.onmessage @ workbench.desktop.main.js:365363
workbench.desktop.main.js:61148 [Extension Host] stack trace: TypeError: Cannot read properties of null (reading 'title')
	at S.sendToSocket (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:45810)
	at S.send (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:45608)
	at S.closeComm (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:41018)
	at l.removeClient (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:62295)
	at t.RSession.removeClient (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:489800)
	at $yzc.closer (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89356:32)
	at $yzc.dispose (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64971:22)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89361:36)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.z (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10792:22)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10815:22)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:493703)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10810:22)
	at l.onStatus (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:65480)
	at S.emit (node:events:526:35)
	at S.setStatus (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:47167)
	at S.onSocketDisconnected (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:42924)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:34104)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10810:22)
	at a.disconnect (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:54154)
	at a.onDisconnectedEvent (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:54390)
	at l.emit (node:events:514:28)
	at /Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:14252 (at console.<anonymous> (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62216:26))
log @ workbench.desktop.main.js:61148
$logExtensionHostMessage @ workbench.desktop.main.js:342302
S @ workbench.desktop.main.js:342953
Q @ workbench.desktop.main.js:342938
M @ workbench.desktop.main.js:342879
L @ workbench.desktop.main.js:342806
(anonymous) @ workbench.desktop.main.js:342669
y @ workbench.desktop.main.js:17356
fire @ workbench.desktop.main.js:17385
fire @ workbench.desktop.main.js:93228
port.onmessage @ workbench.desktop.main.js:365363
workbench.desktop.main.js:466622 [vscode.jupyter-adapter]Cannot read properties of null (reading 'title')
$onExtensionRuntimeError @ workbench.desktop.main.js:466622
S @ workbench.desktop.main.js:342953
Q @ workbench.desktop.main.js:342938
M @ workbench.desktop.main.js:342879
L @ workbench.desktop.main.js:342806
(anonymous) @ workbench.desktop.main.js:342669
y @ workbench.desktop.main.js:17356
fire @ workbench.desktop.main.js:17385
fire @ workbench.desktop.main.js:93228
port.onmessage @ workbench.desktop.main.js:365363
workbench.desktop.main.js:466623 TypeError: Cannot read properties of null (reading 'title')
	at S.sendToSocket (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:45810)
	at S.send (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:45608)
	at S.closeComm (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:41018)
	at l.removeClient (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:62295)
	at t.RSession.removeClient (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:489800)
	at $yzc.closer (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89356:32)
	at $yzc.dispose (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64971:22)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89361:36)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.z (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10792:22)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10815:22)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:493703)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10810:22)
	at l.onStatus (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:65480)
	at S.emit (node:events:526:35)
	at S.setStatus (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:47167)
	at S.onSocketDisconnected (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:42924)
	at UniqueContainer.value (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:34104)
	at $he.y (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10781:26)
	at $he.fire (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10810:22)
	at a.disconnect (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:54154)
	at a.onDisconnectedEvent (/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:54390)
	at l.emit (node:events:514:28)
	at /Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/dist/extension.js:1:14252
```

</details>

---

I think the issue is that we dispose comms (which eventually sends a `comm_close`) when the runtime reaches the `Exited` state, at which point the Jupyter sockets are already closed:

https://github.com/posit-dev/positron/blob/599b6c4af25998a6dd2fca04fc2fb611b22a5644/src/vs/workbench/api/common/positron/extHostLanguageRuntime.ts#L785-L789

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.03.0-48
    OS Version          : OSX

### Test scenario(s) 

No console errors after shutting down runtimes after plotting.

Link(s) to TestRail test cases run or created:
