### ISSUE TITLE
Quarto version not updated on the bottom bar after updating Quarto CLI while Positron is open

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [posit-dev/positron#4083]
## Positron Version:

2024.07.0 (Universal) build 81

## Steps to reproduce the issue:

1. Open Positron, then update Quarto CLI
2. Go to Terminal and type `quarto --version`

The updated version shown in the Terminal does not match the version shown on the bottom bar of Quarto, which was the version when Positron first launched.

<img width="400" alt="Screenshot 2024-07-19 at 10 17 33 AM" src="https://github.com/user-attachments/assets/79199495-e900-434d-b7cd-6ef24c798a80">

## What did you expect to happen?

I expected the versions to match, which would require Positron to update the displayed version when Quarto is updated.

## Were there any error messages in the Output panel or Developer Tools console?

There is an error in the Developer Tools console, though I'm not sure if it's related.

```
  ERR Could not find category with ID: undefined: Error: Could not find category with ID: undefined
    at $Ehc.pc (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:649700:23)
    at $Ehc.makeCategoryVisibleWhenAvailable (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:649025:18)
    at $kE.run (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:650153:48)
    at handler (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:148203:52)
    at $wr.invokeFunction (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:128451:24)
    at $kSb.n (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:340046:39)
    at $kSb.executeCommand (vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:340015:33)
    at vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:650788:34
```

**Comment by juliasilge** [comment]
The same thing happens in VS Code itself so we'll want to open this up as a feature request at https://github.com/quarto-dev/quarto/issues:

![Screenshot 2024-07-19 at 10 09 15 AM](https://github.com/user-attachments/assets/5793d857-be13-427f-bde4-1abe50b592cd)

(Feel free to include my screenshot in addition to yours if you open an issue.)

In either Positron or VS Code, if you do "Reload Window" from the command palette, the UI updates correctly.

**Comment by juliasilge** [comment]
Thanks for opening https://github.com/quarto-dev/quarto/issues/487!
