### ISSUE TITLE
Add support for connecting Positron to Windows Services for Linux (WSL) Ubuntu

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4366]
We recently added support to Positron for connecting to Linux hosts over SSH; however, this support does not currently extend to WSL. Many Windows users prefer to run R and Python in WSL Ubuntu instances. 

OpenVSX includes an extension that can be used to do this for VSCodium:

https://github.com/jeanp413/open-remote-wsl

However, like Open Remote SSH, it would need some modification to work with Positron. 

> [!NOTE]
> This specifically refers to running Positron Desktop natively on Windows, and connecting to a headless server component inside WSL. It doesn't mean running a Positron Server in WSL and connecting via a web browser, or running Positron Desktop itself wholly in WSL.

**Comment by GitHunter0** [comment]
WSL connection is a very helpful feature. [Cursor IDE](https://github.com/getcursor/cursor) managed to make **Microsoft WSL** extension to work, I'm not sure but maybe you can use it as a reference.

**Comment by kv9898** [comment]
This is indeed a super needed feature. Would it be possible to move it back to triage?

**Comment by kv9898** [comment]
I notice that I can use the `open-remote-wsl` package normally for my use case (running mojo) if I manually set the positron version in the server download url template:

```
https://github.com/posit-dev/positron/releases/download/2024.11.0-140/positron-reh-${os}-${arch}-2024.11.0-140.tar.gz
```

**Comment by kv9898** [comment]
> @jmcphers This would be super useful. Any updates on plans to support WSL remotes?
> 
> I'd love to see the full remote dev bundle available for Positron https://code.visualstudio.com/docs/remote/remote-overview

In the meantime, would you consider using the Positron WSL extension I posted above? For me, it works smoothly.

**Comment by jonvanausdeln** [comment]
I just tied with daily build and I get error:

```
[Trace  - 21:31:24.345] Server install command stdout:
Error downloading server from https://cdn.posit.co/positron/dailies/reh/x86_64/positron-reh-Linux-x64-2025.11.0-231.tar.gz
fd3a0b3cfc673e35d64c7b89: start
exitCode==66==
listeningOn====
connectionToken====
logFile==/home/jon/.positron-server/.07fb68b6f39bd6e07381a84e52f3ff3fb82f16c2.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1000/==
fd3a0b3cfc673e35d64c7b89: end

[Error  - 21:31:24.345] Error resolving authority
Error: There is no available Positron server with version 2025.11.0-231 for WSL Linux x86_64.
Please check the [system requirements](https://positron.posit.co/remote-ssh.html#system-requirements) and [troubleshooting guides](https://positron.posit.co/remote-ssh.html#how-it-works-troubleshooting).
    at t.installCodeServer (c:\Users\JonVanausdeln\AppData\Local\Programs\Positron\resources\app\extensions\open-remote-wsl\dist\extension.js:1:20671)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async c:\Users\JonVanausdeln\AppData\Local\Programs\Positron\resources\app\extensions\open-remote-wsl\dist\extension.js:1:29208
```

I did check and the binary is there at https://cdn.posit.co/positron/dailies/reh/x86_64/positron-reh-linux-x64-2025.11.0-231.tar.gz

**Comment by kv9898** [comment]
I actually got the same error and got around it by launching Positron from WSL terminal.

**Comment by jmcphers** [comment]
> `positron-reh-Linux` 

Shoot, that should be `linux`. Sorry folks! Fix in #10324.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.11.0-234](https://github.com/posit-dev/positron-builds/releases/tag/2025.11.0-234)
OS Version(s) : Windows 11 (WSL: Ubuntu 24)

### Test scenario(s) 

I am able to connect to my WSL instance as a remote without changing any settings.  R and Python work as expected.

**Comment by agila5** [comment]
Dear all, 

thank you very much for your work, and sorry for the noise. I've just tested positron from within WSL and everything works correctly. Unfortunately, I cannot find out how to connect Positron with the R version which is installed within WSL. Is that possible? I would be happy to create a new issue if relevant. I can also add more details if necessary. 

Fixed and discussed in: https://github.com/posit-dev/positron/discussions/10395

**Comment by juliasilge** [comment]
@agila5 Yes, can you post on https://github.com/posit-dev/positron/discussions with all the relevant details, so we can try to help you out?
