### ISSUE TITLE
Positron reports the wrong Python version if you change the version used in a project

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/positron#4556]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T04:26:51.868Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python

## Describe the issue:

I frequently switch between Python versions in testing and development work in the same project. Positron remembers the Python version from the virtual env from first use, even after if I destroy and recreate the venv and restart the interpreter.

Here's a screen recording of the steps mentioned below.

https://github.com/user-attachments/assets/61429f08-aabf-4413-980e-d9e3da63c939

## Steps to reproduce the issue:

1. Create a virtual environment for a Python version, e.g. 3.12, in a new project.
2. Start the Python interpreter in Positron.
3. Delete the `.venv` and create a new virtual env for a new Python version, e.g. 3.9.
4. Restart the Python interpreter in Positron.
5. On first launch it reports both 3.12 and 3.9; on restarts it reports having launched 3.12 (the original version).

```bash
uv venv -p 3.12
uv pip install ipykernel

# start Positron interpreter and check sys.version
# stop Positron interpreter

rm -rf .venv
uv venv -p 3.9
uv pip install ipykernel

# start Positron interpreter again and check sys.version
```

## Expected or desired behavior:

Positron should report the actual python version in use in the virtual environmet.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by gadenbuie** [comment]
One more detail: when the project is closed and re-opened in Positron (not just "reload window"), the old venv (or another venv) is selected by default and the new venv is available as an interpreter in the dropdown menu. So this resolves the version number confusion but isn't ideal when switching between Python versions.

**Comment by juliasilge** [comment]
Positron does not currently poll the filesystem for runtimes all the time. As a workaround for now, you could try out refreshing the interpreters via the "Python: Select Interpreter" command when you know you have deleted one.

**Comment by gadenbuie** [comment]
> you could try out refreshing the interpreters via the "Python: Select Interpreter" command when you know you have deleted one.

Does that work for you? IIRC I tried this in the screen recording and it doesn't work for me as a work around.

**Comment by juliasilge** [comment]
No, you're right @gadenbuie. Just refreshing is not enough to get Positron to realize the local venv now has a new version of Python. 👍

**Comment by austin3dickey** [comment]
Note that post–ipykernel bundling, this looks a bit worse. Upon starting a new session, you'll get something like this in the console. Here I deleted a Python 3.12 venv and created a 3.11 venv.
```
Python 3.12.8 (Uv: .venv) failed to start up (exit code 1)

The process exited abnormally (exit status: 1)
Traceback (most recent call last):
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/posit/positron_language_server.py", line 10, in <module>
    from positron.positron_ipkernel import (
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/posit/positron/positron_ipkernel.py", line 20, in <module>
    from ipykernel.compiler import get_tmp_directory
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/py3/ipykernel/__init__.py", line 7, in <module>
    from .connect import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/py3/ipykernel/connect.py", line 12, in <module>
    import jupyter_client
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/py3/jupyter_client/__init__.py", line 3, in <module>
    from .asynchronous import AsyncKernelClient
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/py3/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/py3/jupyter_client/asynchronous/client.py", line 8, in <module>
    import zmq.asyncio
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/__init__.py", line 52, in <module>
    from zmq import backend
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/backend/__init__.py", line 30, in <module>
    raise original_error from None
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/backend/__init__.py", line 25, in <module>
    _ns = select_backend(first)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/backend/select.py", line 30, in select_backend
    mod = import_module(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/austin/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import _zmq
  File "/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312/zmq/backend/cython/_zmq.py", line 34, in <module>
    raise ImportError(msg)
ImportError: 
    Attempting to import zmq Cython backend, which has not been compiled.

    This probably means you are importing zmq from its source tree.
    if this is what you want, make sure to do an in-place build first:

        pip install -e '/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312'

    If it is not, then '/Users/austin/repos/positron/extensions/positron-python/python_files/lib/ipykernel/arm64/cp312' is probably on your sys.path,
    when it shouldn't be. Is that your current working directory?

    If neither of those is true and this file is actually installed,
    something seems to have gone wrong with the install!
    Please report at [https://github.com/zeromq/pyzmq/issues](vscode-file://vscode-app/Users/austin/repos/positron/out/vs/code/electron-sandbox/workbench/workbench-dev.html#)
```

**Comment by austin3dickey** [comment]
Earlier I posted about an [error](https://github.com/posit-dev/positron/issues/4556#issuecomment-2887291648) that made this issue worse after we started bundling ipykernel, but as of https://github.com/posit-dev/positron/pull/13172 that doesn't happen anymore and we're back to the mildly inconvenient naming error.
