### ISSUE TITLE
Install positron in debian Debian GNU/Linux 11 (bullseye) , zstd problem

### ISSUE THREAD

**Issue by joscani** [posit-dev/positron#4635]
Hi I try to install Positron deb packages in debian bullseye. (needed for my job) I don't have problems in my own machine (linux mint 21)

## System details:

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

#### Positron and OS details:
Positron-2024.09.0-1.deb

#### Interpreter details:

R version 4.4.1

## Describe the issue:
Problem insalling deb package

## Steps to reproduce the issue:
```bash
sudo gdebi Positron-2024.09.0-1.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done

A next-generation data science IDE.
 Positron is an extensible, polyglot tool for writing code and exploring data
 in Python, R, and other languages.
Do you want to install the software package? [y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
dpkg-deb: error: archive 'Positron-2024.09.0-1.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive Positron-2024.09.0-1.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 Positron-2024.09.0-1.deb
```

**Comment by jmcphers** [comment]
This happens because we build Positron on Ubuntu which defaults to zstd compression. Debian 11 does not support this compression format (that was added in Debian 12). Here's a summary of the problem:

https://gitlab.com/gitlab-org/gitlab/-/issues/422584

We're investigating building Positron on an older Ubuntu to address glibc problems; it may fix this issue too. See #3854 for details.

**Comment by jonvanausdeln** [comment]
@joscani , we have new release ([2024.09.0-45](https://github.com/posit-dev/positron/releases/tag/2024.09.0-45)) that may work for you. Can you please try it out?

**Comment by joscani** [comment]
@jonvanausdeln  It works, but Positron doesn't find R interpreter . But If I enter in the terminal, R works, R is in /usr/bin/R 

And I can't create a new R or python file
any idea?

**Comment by jmcphers** [comment]
@joscani Open up the Developer Tools (_Developer: Toggle Developer Tools_ command in the Command Palette) and check the Console tab -- do you see any errors there? Can you paste what you see?

**Comment by joscani** [comment]
sure

```
DEBUG [Runtime startup] All extensions contributing language runtimes have been activated.
workbench.desktop.main.js:130651 DEBUG [Runtime startup] Phase changed to 'discovering'
workbench.desktop.main.js:130651 DEBUG [Runtime startup] Phase changed to 'complete'
workbench.desktop.main.js:498847 Activating extension 'quarto.quarto' failed: Cannot read properties of undefined (reading 'settings').
$onExtensionActivationError @ workbench.desktop.main.js:498847
workbench.desktop.main.js:130651 DEBUG [Registering Log Channel] File does not exist. Waiting for 1s to retry. file:///home/dev/.config/Positron/logs/20240917T183110/remoteTunnelService.log
workbench.desktop.main.js:130651 DEBUG [Registering Log Channel] File does not exist. Waiting for 1s to retry. file:///home/dev/.config/Positron/logs/20240917T183110/editSessions.log
workbench.desktop.main.js:130661  INFO [perf] Render performance baseline is 31ms
workbench.desktop.main.js:130671  WARN Settings pattern "environment.*" doesn't match any settings
workbench.desktop.main.js:130671  WARN SettingsEditor2: Settings not included in settingsLayout.ts: positron.dataExplorerExperimental, positron.notebooks.usePositronNotebooks, positron.RemoteHostExperimental, positron.viewer.interactivePlotsInViewer, console.inputHistorySize, issueReporter.experimental.auxWindow
workbench.desktop.main.js:130671  WARN Settings pattern "environment.*" doesn't match any settings
workbench.desktop.main.js:130681   ERR command 'r.createNewFile' not found: Error: command 'r.createNewFile' not found
    at $CTb.n (vscode-file://vscode-app/usr/share/positron/resources/app/out/vs/workbench/workbench.desktop.main.js:344131:39)
    at $CTb.executeCommand (vscode-file://vscode-app/usr/share/positron/resources/app/out/vs/workbench/workbench.desktop.main.js:344126:25)
    at async UniqueContainer.value (vscode-file://vscode-app/usr/share/positron/resources/app/out/vs/workbench/workbench.desktop.main.js:385578:21)
2workbench.desktop.main.js:130651 DEBUG Comments: URIs of continue on comments to add to storage .
workbench.desktop.main.js:130651 DEBUG Comments: URIs of continue on comments to add to storage .
```

**Comment by joscani** [comment]
hi. I'm just install quarto in debian, and now Positron works. Thanks 
I think this is a prerrequisite

**Comment by joscani** [comment]
No. Sorry. 
the problem is with glibc 

```
extension vscode.positron-r for language ID r
workbench.desktop.main.js:498847 Activating extension 'vscode.jupyter-adapter' failed: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/share/positron/resources/app/extensions/jupyter-adapter/prebuilds/linux-x64/node.napi.glibc.node).
workbench.desktop.main.js:498847 Cannot activate the 'Positron Python' extension because its dependency 'Positron Jupyter Adapter' failed to activate
workbench.desktop.main.js:498847 Cannot activate the 'R' extension because its dependency 'Positron Jupyter Adapter' failed to activate```

**Comment by joscani** [comment]
Can anyone reopen the issue?
