### ISSUE TITLE
Smoketest for New Project Wizard Python with git init fails on Ubuntu 

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#4639]
```
  29 passing (4m)
  1 failing

  1) VSCode Smoke Tests (Electron)
       New Project Wizard
         Python - New Project Wizard
           Default Python Project with git init [C674522] #pr:
     Error: Timeout: get terminal buffer '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/home/user/dev/git/posit/positron/test/automation/out/code.js:204:23)
      at async Code.waitForTerminalBuffer (/home/user/dev/git/posit/positron/test/automation/out/code.js:175:9)
      at async Terminal._waitForTerminal (/home/user/dev/git/posit/positron/test/automation/out/terminal.js:282:9)
      at async Terminal.runCommand (/home/user/dev/git/posit/positron/test/automation/out/terminal.js:79:17)
      at async Terminal.createTerminal (/home/user/dev/git/posit/positron/test/automation/out/terminal.js:126:9)
      at async Context.<anonymous> (out/areas/positron/new-project-wizard/new-project.test.js:158:17)
```

**Comment by petetronic** [comment]
With tracing on, Playwright screen capture shows a toast notification over the Terminal window and the test times out before it can run `git status` in the Terminal and look for "On branch main" in the text.

**Comment by petetronic** [comment]
![page@314b5625f9b881fb12ff394a97783f15-1726061138 713287](https://github.com/user-attachments/assets/295332e7-97dc-458a-8bd1-41ebb6b75917)

**Comment by petetronic** [comment]
I also had ENV set for `POSITRON_PY_VER_SEL=3.11.9` so I'm not sure why the Python version is the global 3.12.3?

**Comment by petetronic** [comment]
There isn't a trace screen that shows the state of the project configuration for the interpreter unfortunately, the last view is:
![page@314b5625f9b881fb12ff394a97783f15-1726061123 448016](https://github.com/user-attachments/assets/a57c620a-b867-4e49-bd38-dcbdb1de15c1)

**Comment by petetronic** [comment]
The issue was .bashrc had entries that were taking far too long to start up a terminal shell, this was a local issue and not a Positron issue. Closing.
