### ISSUE TITLE
Ark virtual documents can't be opened on Windows

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#4651]
#### Positron and OS details:

Positron Version: 2024.09.0 (system setup) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:49.688Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R version 4.4.1 (2024-06-14 ucrt)

## Describe the issue:

Having attached usethis via `library(usethis)`, I've done `debug(git_sitrep)`.
Then I call `git_sitrep()` and that temporary file we use to provide the source of usethis, in this case, cannot be found.

First I see this:

<img width="781" alt="Screenshot 2024-09-11 at 3 33 47 PM" src="https://github.com/user-attachments/assets/2a17bc5e-4b56-4075-8ea1-8089fb5afd82">

If I click on "Try Again", I see this:

<img width="563" alt="Screenshot 2024-09-11 at 3 33 58 PM" src="https://github.com/user-attachments/assets/3ec78425-fc25-4f13-a874-bc16d3532702">

## Steps to reproduce the issue:

I originally discovered it like so, in the R Console:

```r
library(usethis)
debug(git_sitrep)
git_sitrep()
```

But I suspect you can experience with any function and package you like. I've tried several. I suppose it's important to note that I have not installed _any_ packages from source yet in this machine, so I've got no srcrefs.

## Expected or desired behavior:

I expect to be able to step through the source as I do on macOS.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

In Developer Console I've got this:

```
ERR Error: Unable to read file 'c:\Users\jenny\ark:namespace:usethis.R' (Error: Unable to resolve nonexistent file 'c:\Users\jenny\ark:namespace:usethis.R')
    at $5q.F (workbench.desktop.main.js:132844:20)
    at $5q.C (workbench.desktop.main.js:132833:28)
    at async $gzc.M (workbench.desktop.main.js:602268:32)
    at async $gzc.readStream (workbench.desktop.main.js:602249:45)
    at async $fTb.Db (workbench.desktop.main.js:584192:33)
    at async $fTb.resolve (workbench.desktop.main.js:584074:13)
    at async $epc.W (workbench.desktop.main.js:601965:17)
    at async $Y8b.jb (workbench.desktop.main.js:482524:17)
    at async $e9b.setInput (workbench.desktop.main.js:580746:39)
    at async $$Rb.S (workbench.desktop.main.js:577764:17)
    at async $$Rb.L (workbench.desktop.main.js:577627:44)
    at async $$Rb.openEditor (workbench.desktop.main.js:577526:24)
    at async workbench.desktop.main.js:615158:65
```

**Comment by lionel-** [comment]
The support for `View()`ing functions from https://github.com/posit-dev/positron/pull/8262 also suffers from the problem if the function is from an installed package. To reproduce:

```r
View(data.frame)
```

**Comment by lionel-** [comment]
It's because we're sending `ark:` URIs via the `path` field in https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source

Instead we should be using the `source_reference` field. This field takes an ID, not a URI, so we'll need to map Ark URIs to IDs and send the latter to the client. The mapping will be cleaned up on session end.

Edit: Actually the `ark:` URIs should be okay, they are detected here: https://github.com/microsoft/vscode/blob/aae2b0d4c589c367437411b5e6eb8ddf0386476f/src/vs/workbench/contrib/debug/common/debugSource.ts#L142-L144

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.09.0-126](https://github.com/posit-dev/positron-builds/releases/tag/2025.09.0-126)
OS Version(s) : Windows 11

### Test scenario(s) 

I able to step through now without issue

<img width="857" height="324" alt="Image" src="https://github.com/user-attachments/assets/adac81b7-d6ae-4350-bfc4-4f65c90b9218" />

**Comment by rmflight** [comment]
I was also seeing this issue on Linux, with source installed packages via `renv`. Looking forward to the next official release to have proper follow through when debugging.

**Comment by lionel-** [comment]
@rmflight Interesting, please let us know if the next release doesn't fix it
