### ISSUE TITLE
Improve Plotly Support - With large plotly notebook, some plots render incompletely

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5311]
## Acceptance Criteria

Improve plotly support so that there are no errors when rendering plotly graphs.  See related ticket. https://github.com/posit-dev/positron/issues/11859

#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 12
OSX

#### Interpreter details:

Python 3.10.12

## Describe the issue:

When the large notebook https://github.com/posit-dev/qa-example-content/blob/main/workspaces/large_py_notebook/spotify.ipynb is run, some of the plotly plots render incompletely:

![Image](https://github.com/user-attachments/assets/0cf158c7-5448-41e3-a795-fe4c502db005)

![Image](https://github.com/user-attachments/assets/ea6e635b-ba0c-4739-8eea-8c0c611d5887)

Note that this also happens with VSCode.

## Steps to reproduce the issue:

1. Run the test notebook
2.Scroll through the plots, looking for incomplete plots
3. Note that sometimes a re-run can help, but it doesn't always

## Expected or desired behavior:

All plots render completely.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Not sure this is related, but:

  ERR Error: Notebook too large to backup
    at $HKb.snapshot (workbench.desktop.main.js:612819:31)
    at async $sF.backup (workbench.desktop.main.js:612120:27)
    at async workbench.desktop.main.js:582982:40

**Comment by cindyytong** [comment]
Moving to 2026 backlog to monitor user reported issues
