### ISSUE TITLE
R runtime shutdown timeouts during smoke tests

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5334]
#### Positron and OS details:

Main on 11/12/24
Ubuntu

#### Interpreter details:

R 4.4.0

## Describe the issue:

Shortly after notebook creation and entry of first cell contents:

![Image](https://github.com/user-attachments/assets/fd853613-3a14-4bbf-8ca3-17e0ed758ff1)

Test run archive:
[notebookCreate.test.js.zip](https://github.com/user-attachments/files/17718170/notebookCreate.test.js.zip)

CI job:
https://github.com/posit-dev/positron/actions/runs/11790508005/job/32841062065

## Steps to reproduce the issue:

This is currently only reproing in the Notebook Create - R smoke test.  It has happened about three times recently:

https://github.com/posit-dev/positron/actions/runs/11696991953/job/32574999492
https://github.com/posit-dev/positron/actions/runs/11716383905/attempts/1
https://github.com/posit-dev/positron/actions/runs/11790508005/job/32841062065

## Expected or desired behavior:

Normal notebook operation

## Were there any error messages in the UI, Output panel, or Developer Tools console?

ERR NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook': Error: NO notebook document for 'untitled:Untitled-1.ipynb?jupyter-notebook'
	at ExtHostNotebookController.getNotebookDocument (/home/runner/work/positron/positron/out/vs/workbench/api/common/extHostNotebook.js:114:23)
	at ExtHostNotebookKernels.$cancelCells (/home/runner/work/positron/positron/out/vs/workbench/api/common/extHostNotebookKernels.js:381:52)
	at RPCProtocol._doInvokeHandler (/home/runner/work/positron/positron/out/vs/workbench/services/extensions/common/rpcProtocol.js:425:27)
	at RPCProtocol._invokeHandler (/home/runner/work/positron/positron/out/vs/workbench/services/extensions/common/rpcProtocol.js:410:45)
	at RPCProtocol._receiveRequest (/home/runner/work/positron/positron/out/vs/workbench/services/extensions/common/rpcProtocol.js:351:32)
	at RPCProtocol._receiveOneMessage (/home/runner/work/positron/positron/out/vs/workbench/services/extensions/common/rpcProtocol.js:278:26)
	at UniqueContainer.value (/home/runner/work/positron/positron/out/vs/workbench/services/extensions/common/rpcProtocol.js:141:67)
	at Emitter._deliver (/home/runner/work/positron/positron/out/vs/base/common/event.js:967:26)
	at Emitter.fire (/home/runner/work/positron/positron/out/vs/base/common/event.js:996:22)
	at BufferedEmitter.fire (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:486:35)
	at UniqueContainer.value (/home/runner/work/positron/positron/out/vs/workbench/api/node/extensionHostProcess.js:228:41)
	at Emitter._deliver (/home/runner/work/positron/positron/out/vs/base/common/event.js:967:26)
	at Emitter.fire (/home/runner/work/positron/positron/out/vs/base/common/event.js:996:22)
	at BufferedEmitter.fire (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:486:35)
	at PersistentProtocol._receiveMessage (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:757:45)
	at UniqueContainer.value (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:632:82)
	at Emitter._deliver (/home/runner/work/positron/positron/out/vs/base/common/event.js:967:26)
	at Emitter.fire (/home/runner/work/positron/positron/out/vs/base/common/event.js:996:22)
	at ProtocolReader.acceptChunk (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:275:37)
	at UniqueContainer.value (/home/runner/work/positron/positron/out/vs/base/parts/ipc/common/ipc.net.js:242:61)
	at Emitter._deliver (/home/runner/work/positron/positron/out/vs/base/common/event.js:967:26)
	at Emitter.fire (/home/runner/work/positron/positron/out/vs/base/common/event.js:996:22)
	at WebSocketFlowManager._processReadQueue (/home/runner/work/positron/positron/out/vs/base/parts/ipc/node/ipc.net.js:519:34)

**Comment by jonvanausdeln** [comment]
We aren't seeing this in CI test now (after merge)

**Comment by jonvanausdeln** [comment]
We still seeing this issue..
https://github.com/posit-dev/positron/actions/runs/11864129344/job/33066962284

**Comment by petetronic** [comment]
@seeM after we address https://github.com/posit-dev/positron/issues/2671 we could work with QA to see if this issue subsides in CI?

**Comment by seeM** [comment]
@petetronic Yes, I think this issue may be a duplicate of https://github.com/posit-dev/positron/issues/4043 which I'm hoping to fix as part of the notebook session stability work.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : multiple, but including 2025.01.0-10
    OS Version          : ubuntu

### Test scenario(s) 

Have not seen this in automation in a while

Link(s) to TestRail test cases run or created:
