### ISSUE TITLE
Installing siuba into a venv keeps that Positron interpreter from starting

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5411]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 41
Code - OSS Version: 1.93.0
Commit: 39536c265d6828a68291984d0d359170316d055e
Date: 2024-11-18T02:47:29.611Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

So far I have mostly been trying this with pyenv and 3.10, 3.11, and 3.12.

## Describe the issue:

If I install [siuba](https://siuba.org/) into a venv, then I cannot start that venv in Positron. I see the "HTTP request failed" error:

![Image](https://github.com/user-attachments/assets/b14efcfa-a0a3-4c47-af8a-a307619eb517)

If I take a previously existing venv and I additionally install siuba into it, then that venv no longer can start in Positron and it is busted.

## Steps to reproduce the issue:

1. Take a currently existing venv and activate it
2. `pip install siuba`
3. Try to choose this venv in Positron
4. Be sad 😭 

## Expected or desired behavior:

The venv should start in Positron. Do we have [incompatible requirements](https://github.com/machow/siuba/blob/main/requirements.txt)?

## Were there any error messages in the UI, Output panel, or Developer Tools console?

The "HTTP request failed" error is in the Extension Host channel. Also I see "Starting language runtime failed. Reason: HTTP request failed" in the Developer Tools.

**Comment by juliasilge** [comment]
@ntluong95 Do you have any examples or steps that cause it to happen for you?

**Comment by ntluong95** [comment]
I don't have time to make a reproducible example but here is what I have
![Image](https://github.com/user-attachments/assets/bd04d440-be8a-4553-923b-ffc4aea2ceff)

My pyproject.toml
![Image](https://github.com/user-attachments/assets/1acf068d-e7a2-4d18-ab5e-f25b2c5703aa)

It is always unreliable to let Positron start Python in my computer (Windows), the alternative `Ctrl + Shift + p -> Select Python interpreter` works more stable for me. The UI usually doesn't help

**Comment by juliasilge** [comment]
With a new build I got more info:

Positron Version: 2024.12.0 (Universal) build 88
Code - OSS Version: 1.93.0
Commit: 54cbc06c099bc8910011bc31c3586fb1882d2fd2
Date: 2024-11-27T02:47:26.609Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

```
Python 3.10.13 (Venv: .venv) starting.
Python 3.10.13 (Venv: .venv) failed to start up (exit code 1)

The process exited abnormally (exit status: 1)
Traceback (most recent call last):
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_language_server.py", line 13, in <module>
    from positron_ipykernel.positron_ipkernel import (
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_ipykernel/positron_ipkernel.py", line 31, in <module>
    from .access_keys import encode_access_key
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_ipykernel/access_keys.py", line 9, in <module>
    from .inspectors import INSPECTOR_CLASSES, PositronInspector, get_inspector
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_ipykernel/inspectors.py", line 44, in <module>
    from .third_party import np_, pd_, torch_
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_ipykernel/third_party.py", line 64, in <module>
    pd_ = _get_pandas()
  File "/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/positron/positron_ipykernel/third_party.py", line 22, in _get_pandas
    import pandas
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/Users/juliasilge/Work/posit/python-testing-envs/siuba-testing/.venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Is it the version of numpy?

**Comment by ntluong95** [comment]
I think the siuba project has been deactivated for a while, and it didn't keep update with pandas arrow backend anymore
