### ISSUE TITLE
IPyWidgets don't work in notebooks

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5463]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 55
Code - OSS Version: 1.93.0
Commit: a181837fc1d5fd55f7ed377d89d3fce286a318d7
Date: 2024-11-22T02:46:25.203Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Any Python.

## Steps to reproduce the issue:

1. Create a Python notebook.
2. Create and display an IPyWidget:

    ```python
    import ipywidgets
    w = ipywidgets.IntSlider()
    w
    ```

The cell's execution indicator will be a red cross.

## Expected or desired behavior:
It should show the slider.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
```

$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
_doInvokeHandler @ rpcProtocol.ts:475
_invokeHandler @ rpcProtocol.ts:460
_receiveRequest @ rpcProtocol.ts:390
_receiveOneMessage @ rpcProtocol.ts:316
(anonymous) @ rpcProtocol.ts:161
_deliver @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
port.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: INVALID mime type: buffer_paths. Must be in the format "type/subtype[;optionalparameter]"
	at new NotebookCellOutputItem (/Users/seem/posit/positron/out/vs/workbench/api/common/extHostTypes.js:3187:23)
	at NotebookCellOutputItem.text (/Users/seem/posit/positron/out/vs/workbench/api/common/extHostTypes.js:3176:20)
	at handleRuntimeMessageOutput (/Users/seem/posit/positron/extensions/positron-notebook-controllers/out/notebookController.js:346:68)
	at NotebookController.handleMessageForCellExecution (/Users/seem/posit/positron/extensions/positron-notebook-controllers/out/notebookController.js:184:23)
	at Object.callback (/Users/seem/posit/positron/extensions/positron-notebook-controllers/out/notebookController.js:165:43)
	at /Users/seem/posit/positron/extensions/positron-notebook-controllers/out/notebookController.js:224:31
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.12.0-77
OS Version(s) : MacOS

### Test scenario(s) 
Confirmed that iPyWidget render as expected via notebook cell. 👍 

### Link(s) to TestRail test cases run or created: 

n/a
