### ISSUE TITLE
In a notebook, unable to save changes to layers with LeafMap

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5520]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 80
OSX

#### Interpreter details:

Python 3.10.12

## Describe the issue:

Using (LeafMap section):
[Plots and Widgets Notebook](https://github.com/posit-dev/qa-example-content/blob/main/workspaces/python-plots-widgets-notebook/plots-widgets-notebook.ipynb)

![Image](https://github.com/user-attachments/assets/fae75606-a0c4-49ca-88d2-2c0c71820fa4)

Unable to save layer edits (see repro steps).

## Steps to reproduce the issue:

1. Run the LeafMap section of [Plots and Widgets Notebook](https://github.com/posit-dev/qa-example-content/blob/main/workspaces/python-plots-widgets-notebook/plots-widgets-notebook.ipynb)
2. Draw a rectangle on it
3. Click the trash can icon
4. Click the rectangle
5. Attempt to save changes
6. Note that small popup with Save/Cancel/Clear All does not go away

## Expected or desired behavior:

Expected to be able to delete an added layer.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

index.html?id=183780…otebookRenderer:332 Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': function(t){return t?.properties.style} could not be cloned.
    at HostMessaging.postMessage (vscode-webview://1a3g1f34slfks2msbo01jueqa7ivgk56tlpuogagf5008lb6bmj5/index…arentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:332:24)
    at <computed> (vscode-webview://1a3g1f34slfks2msbo01jueqa7ivgk56tlpuogagf5008lb6bmj5/index…rentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:1314:21)
    at doPostMessage (<anonymous>:5:8)
    at Object.postMessage (<anonymous>:19:10)
    at postNotebookMessage (notebookWebviewPreloads.js:2314:20)
    at context.postMessage (notebookWebviewPreloads.js:1550:54)
    at yg.postMessage (https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Cont…ources/app/extensions/positron-ipywidgets/renderer/media/index.js:89:11322)
    at qc.send (https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Cont…sources/app/extensions/positron-ipywidgets/renderer/media/index.js:89:5769)
    at Lo.send (https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Cont…urces/app/extensions/positron-ipywidgets/renderer/media/index.js:73:200705)
    at Mo.send (https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Cont…urces/app/extensions/positron-ipywidgets/renderer/media/index.js:73:206759)

**Comment by nstrayer** [comment]
I get the exact same behavior on vscode. I think this is a leafmap problem, not an IDE one. 

<img width="631" alt="Image" src="https://github.com/user-attachments/assets/77afa50e-97cc-47dc-91ac-890e9df18bec" />
