### ISSUE TITLE
positron-duckdb extension fails to load after v1.95 upstream merge

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#5742]
Positron's quick viewing of data store files (.csv, .parquet, etc) in the data explorer is not working after the merge of v1.95 upstream.

The extension host output shows an error loading the `positron.positron-duckdb` extension:

```
2024-12-14 15:53:08.808 [info] ExtensionService#_doActivateExtension positron.positron-duckdb, startup: false, activationEvent: 'onStartupFinished'
2024-12-14 15:53:08.810 [error] Activating extension positron.positron-duckdb failed due to an error:
2024-12-14 15:53:08.810 [error] Error: Cannot find module '@duckdb/duckdb-wasm'
Require stack:
- /Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js
- /Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
	at n._resolveFilename (node:electron/js2c/utility_init:2:16068)
	at Function.resolveFilename [as _resolveFilename] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83602:38)
	at Module._load (node:internal/modules/cjs/loader:1058:27)
	at c._load (node:electron/js2c/node_init:2:16955)
	at Module._load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86483:25)
	at Function.load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83589:29)
	at Function.load [as _load] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79847:25)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at 562 (/Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:25346)
	at s (/Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:25657)
	at 256 (/Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:1458)
	at s (/Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:25657)
	at /Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:25697
	at Object.<anonymous> (/Applications/Positron.app/Contents/Resources/app/extensions/positron-duckdb/dist/extension.js:1:25802)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at Module._load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86483:25)
	at Function.load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83589:29)
	at Function.load [as _load] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79847:25)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at $qKc.xb (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83657:11)
	at async Promise.all (index 0)
```

**Comment by petetronic** [comment]
This issue was observed on both macOS and Windows

**Comment by wesm** [comment]
Is this only in release builds? It loads for me on Linux in a development build, but maybe it has something to do with the webpack configuration for this extension

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Duckdb opens work again

Link(s) to TestRail test cases run or created:
