### ISSUE TITLE
Error in positron-proxy extension initialization after v1.95 upstream merge

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#5743]
With the merge of v1.95 upstream, the help service is failing likely due to the following error shown in the extension host output on initializing the `positron-proxy` extension:

```
2024-12-14 15:53:07.525 [info] ExtensionService#_doActivateExtension positron.positron-proxy, startup: false, activationEvent: 'onCommand:positronProxy.setHelpProxyServerStyles'
2024-12-14 15:53:07.530 [error] Activating extension positron.positron-proxy failed due to an error:
2024-12-14 15:53:07.530 [error] Error: Cannot find module 'express'
Require stack:
- /Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js
- /Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
	at n._resolveFilename (node:electron/js2c/utility_init:2:16068)
	at Function.resolveFilename [as _resolveFilename] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83602:38)
	at Module._load (node:internal/modules/cjs/loader:1058:27)
	at c._load (node:electron/js2c/node_init:2:16955)
	at Module._load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86483:25)
	at Function.load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83589:29)
	at Function.load [as _load] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79847:25)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at 8064 (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:89378)
	at r (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:90141)
	at 9915 (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:83426)
	at r (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:90141)
	at 5256 (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:81265)
	at r (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:90141)
	at /Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:90181
	at Object.<anonymous> (/Applications/Positron.app/Contents/Resources/app/extensions/positron-proxy/dist/extension.js:2:90287)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at Module._load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86483:25)
	at Function.load (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83589:29)
	at Function.load [as _load] (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79847:25)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at $qKc.xb (file:///Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83657:11)
	at async Promise.all (index 0)
```

**Comment by petetronic** [comment]
This issue was observed on both macOS and Windows

**Comment by jmcphers** [comment]
May be related to this comment about the Yarn => Npm transition from upstream:

https://github.com/posit-dev/positron/blob/240e51fa165f6c512e586f0af105a0c8fc092607/build/lib/extensions.ts#L108-L112

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

?load from console for R and Python

Link(s) to TestRail test cases run or created:
